platform:ios, '7.0'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'SVProgressHUD'
pod 'YTKKeyValueStore'
pod 'ReactiveCocoa'
pod 'TheSidebarController'
pod 'EasyIOS', '~> 2.2.2'
pod 'EasyIOS-Extention', '~> 1.2'
